services:
  restic-ui:
    build: .
    container_name: restic-ui
    ports:
      - "5015:8000"
    env_file:
      - /fs/backblaze.env
    environment:
      FLASK_ENV: production
    volumes:
      - /etc/restic-password:/etc/restic-password
      - /usr/bin/restic:/usr/bin/restic
    restart: unless-stopped
